spring:
  application:
    name: pi
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
    include: secret, s3
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  mail:
    host: ${SPRING__MAIL__HOST}
    port: ${SPRING__MAIL__PORT}
    username: ${SPRING__MAIL__USERNAME}
    password: ${SPRING__MAIL__PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB