spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
app:
  cookie:
    domain: ""         # dev: 도메인 미설정(HostOnly). 절대 'localhost' 넣지 않기
    secure: false
    sameSite: Lax